[project]
name = "wb-api-sdk"
version = "0.1.0"
description = "Python SDK for Wildberries API"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.0",
    "ijson>=3.4.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
